### ISSUE TITLE
Need more content!!!!!!

### ISSUE THREAD

**Issue by HysteriaShoot** [gaarlos/Java-repaso#1]
I can pass you my folder with the compilation of the great Java successes

**Comment by gaarlos** [comment]
Ye pls <3 @HysteriaShoot

**Comment by HysteriaShoot** [comment]
https://drive.google.com/file/d/1XlzB8l6pBlz5zg-y00HgbiWUTTAK9wl5/view?usp=sharing

I have more in photos. Do you want it? I use it to study in September
